/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    hero: Hero;
    textBlock: TextBlock;
    formBlock: FormBlock;
    relatedBlocks: RelatedBlocks;
    group: Group;
    imageBlock: ImageBlock;
    buttons: Buttons;
  };
  collections: {
    media: Media;
    pages: Page;
    posts: Post;
    users: User;
    sessions: Session;
    accounts: Account;
    verifications: Verification;
    passkeys: Passkey;
    forms: Form;
    submissions: Submission;
    'form-uploads': FormUpload;
    navigation: Navigation;
    menu_item: MenuItem;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    verifications: VerificationsSelect<false> | VerificationsSelect<true>;
    passkeys: PasskeysSelect<false> | PasskeysSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    'form-uploads': FormUploadsSelect<false> | FormUploadsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    menu_item: MenuItemSelect<false> | MenuItemSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    settings: Setting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  variant: 'primary' | 'secondary' | 'tertiary';
  theme?: ('light' | 'dark' | 'primary' | 'secondary' | 'tertiary') | null;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  quality?: number | null;
  /**
   * Optimize image to WebP format
   */
  optimise?: boolean | null;
  /**
   * Width of the image
   */
  resizeWidth?: number | null;
  /**
   * Height of the image
   */
  resizeHeight?: number | null;
  /**
   * How to fit the image
   */
  fit?: ('cover' | 'contain' | 'fill' | 'inside' | 'outside') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textBlock".
 */
export interface TextBlock {
  theme?: ('light' | 'dark' | 'primary' | 'secondary' | 'tertiary') | null;
  variant: 'primary' | 'secondary' | 'tertiary';
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  buttons?:
    | {
        button: {
          type?: ('url' | 'internal' | 'email' | 'tel' | 'download' | 'custom') | null;
          url?: string | null;
          internal?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          email?: string | null;
          tel?: string | null;
          download?: {
            relationTo: 'media';
            value: string | Media;
          } | null;
          custom?: string | null;
          text: string;
          href?: string | null;
          variant: 'default' | 'ghost' | 'link' | 'outline' | 'secondary';
          target?: '_blank' | null;
        };
        id?: string | null;
      }[]
    | null;
  image?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  _order?: string | null;
  title: string;
  description?: string | null;
  image?: (string | null) | Media;
  blocks?: (Hero | TextBlock)[] | null;
  article?: {
    blocks?: (Hero | TextBlock | FormBlock | RelatedBlocks | ImageBlock)[] | null;
  };
  listing?: {
    list?: ('pages' | 'posts' | 'children') | null;
    /**
     * The number of items to display
     */
    limit?: number | null;
    items?:
      | (
          | {
              relationTo: 'pages';
              value: string | Page;
            }
          | {
              relationTo: 'posts';
              value: string | Post;
            }
        )[]
      | null;
    footer?: (Hero | TextBlock | FormBlock | RelatedBlocks | ImageBlock)[] | null;
  };
  contact?: {
    blocks?: (Hero | TextBlock | FormBlock | RelatedBlocks | ImageBlock)[] | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    /**
     * Canonical URL for this page
     */
    canonical?: string | null;
    robots?: {
      nofollow?: boolean | null;
      noindex?: boolean | null;
      noarchive?: boolean | null;
      nocache?: boolean | null;
      /**
       * Additional robots directives
       */
      extras?: string | null;
    };
    languageAlternates?:
      | {
          href: string;
          hrefLang: string;
          id?: string | null;
        }[]
      | null;
    openGraph?: {
      basic?: {
        title?: string | null;
        type?: string | null;
        /**
         * Open Graph image
         */
        image?: (string | null) | Media;
        url?: string | null;
      };
      optional?: {
        audio?: string | null;
        description?: string | null;
        determiner?: string | null;
        locale?: string | null;
        localeAlternate?:
          | {
              locale: string;
              id?: string | null;
            }[]
          | null;
        siteName?: string | null;
        video?: string | null;
      };
      /**
       * Additional image properties (optional)
       */
      image?: {
        /**
         * MIME type (e.g., image/jpeg)
         */
        type?: string | null;
        width?: number | null;
        height?: number | null;
        alt?: string | null;
      };
      article?: {
        publishedTime?: string | null;
        modifiedTime?: string | null;
        expirationTime?: string | null;
        authors?:
          | {
              author: string;
              id?: string | null;
            }[]
          | null;
        section?: string | null;
        tags?:
          | {
              tag: string;
              id?: string | null;
            }[]
          | null;
      };
    };
    twitter?: {
      card?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
      /**
       * Twitter @username for the site
       */
      site?: string | null;
      /**
       * Twitter @username for the content creator
       */
      creator?: string | null;
      title?: string | null;
      description?: string | null;
      /**
       * Twitter card image
       */
      image?: (string | null) | Media;
      /**
       * Alt text for the Twitter image
       */
      imageAlt?: string | null;
    };
    extend?: {
      link?:
        | {
            rel?: string | null;
            href?: string | null;
            hreflang?: string | null;
            type?: string | null;
            id?: string | null;
          }[]
        | null;
      meta?:
        | {
            name?: string | null;
            property?: string | null;
            content?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  template?: ('default' | 'article' | 'listing' | 'contact') | null;
  author: string | User;
  theme?: ('light' | 'dark' | 'primary' | 'secondary' | 'tertiary') | null;
  menu?: (string | null) | Navigation;
  parent?: (string | null) | Page;
  breadcrumbs?:
    | {
        doc?: (string | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formBlock".
 */
export interface FormBlock {
  theme?: ('light' | 'dark' | 'primary' | 'secondary' | 'tertiary') | null;
  variant: 'primary' | 'secondary' | 'tertiary';
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "relatedBlocks".
 */
export interface RelatedBlocks {
  theme?: ('light' | 'dark' | 'primary' | 'secondary' | 'tertiary') | null;
  variant: 'primary' | 'secondary' | 'tertiary';
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  related?:
    | (
        | {
            relationTo: 'pages';
            value: string | Page;
          }
        | {
            relationTo: 'posts';
            value: string | Post;
          }
      )[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'relatedBlocks';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  description?: string | null;
  image?: (string | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    /**
     * Canonical URL for this page
     */
    canonical?: string | null;
    robots?: {
      nofollow?: boolean | null;
      noindex?: boolean | null;
      noarchive?: boolean | null;
      nocache?: boolean | null;
      /**
       * Additional robots directives
       */
      extras?: string | null;
    };
    languageAlternates?:
      | {
          href: string;
          hrefLang: string;
          id?: string | null;
        }[]
      | null;
    openGraph?: {
      basic?: {
        title?: string | null;
        type?: string | null;
        /**
         * Open Graph image
         */
        image?: (string | null) | Media;
        url?: string | null;
      };
      optional?: {
        audio?: string | null;
        description?: string | null;
        determiner?: string | null;
        locale?: string | null;
        localeAlternate?:
          | {
              locale: string;
              id?: string | null;
            }[]
          | null;
        siteName?: string | null;
        video?: string | null;
      };
      /**
       * Additional image properties (optional)
       */
      image?: {
        /**
         * MIME type (e.g., image/jpeg)
         */
        type?: string | null;
        width?: number | null;
        height?: number | null;
        alt?: string | null;
      };
      article?: {
        publishedTime?: string | null;
        modifiedTime?: string | null;
        expirationTime?: string | null;
        authors?:
          | {
              author: string;
              id?: string | null;
            }[]
          | null;
        section?: string | null;
        tags?:
          | {
              tag: string;
              id?: string | null;
            }[]
          | null;
      };
    };
    twitter?: {
      card?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
      /**
       * Twitter @username for the site
       */
      site?: string | null;
      /**
       * Twitter @username for the content creator
       */
      creator?: string | null;
      title?: string | null;
      description?: string | null;
      /**
       * Twitter card image
       */
      image?: (string | null) | Media;
      /**
       * Alt text for the Twitter image
       */
      imageAlt?: string | null;
    };
    extend?: {
      link?:
        | {
            rel?: string | null;
            href?: string | null;
            hreflang?: string | null;
            type?: string | null;
            id?: string | null;
          }[]
        | null;
      meta?:
        | {
            name?: string | null;
            property?: string | null;
            content?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  theme?: ('light' | 'dark' | 'primary' | 'secondary' | 'tertiary') | null;
  author: string | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  email: string;
  /**
   * Profile image URL
   */
  image?: string | null;
  /**
   * admin or user
   */
  role?: ('admin' | 'editor' | 'contributor' | 'member' | 'user') | null;
  emailVerified?: boolean | null;
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imageBlock".
 */
export interface ImageBlock {
  theme?: ('light' | 'dark' | 'primary' | 'secondary' | 'tertiary') | null;
  variant: 'primary' | 'secondary' | 'tertiary';
  image?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  items?: NavigationMenuItem[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavigationMenuItem".
 */
export interface NavigationMenuItem {
  id: string;
  title: string;
  type: string;
  href: string;
  depth: number;
  collapsed: boolean;
  parent: string | null;
  children?: NavigationMenuItem[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "group".
 */
export interface Group {
  variant: 'primary' | 'secondary' | 'tertiary';
  blocks?: (TextBlock | FormBlock | RelatedBlocks | ImageBlock)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'group';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buttons".
 */
export interface Buttons {
  buttons?:
    | {
        button: {
          type?: ('url' | 'internal' | 'email' | 'tel' | 'download' | 'custom') | null;
          url?: string | null;
          internal?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          email?: string | null;
          tel?: string | null;
          download?: {
            relationTo: 'media';
            value: string | Media;
          } | null;
          custom?: string | null;
          text: string;
          href?: string | null;
          variant: 'default' | 'ghost' | 'link' | 'outline' | 'secondary';
          target?: '_blank' | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'buttons';
}
/**
 * Auto-generated from Better Auth schema (session)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: string;
  expiresAt: string;
  token: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  user: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (account)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: string;
  accountId: string;
  providerId: string;
  user: string | User;
  accessToken?: string | null;
  refreshToken?: string | null;
  idToken?: string | null;
  accessTokenExpiresAt?: string | null;
  refreshTokenExpiresAt?: string | null;
  scope?: string | null;
  password?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (verification)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications".
 */
export interface Verification {
  id: string;
  identifier: string;
  value: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (passkey)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "passkeys".
 */
export interface Passkey {
  id: string;
  name?: string | null;
  publicKey: string;
  user: string | User;
  credentialID: string;
  counter: number;
  deviceType: string;
  backedUp: boolean;
  transports?: string | null;
  aaguid?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Form fields become locked once a form has submissions or connected data
   */
  locked?: boolean | null;
  pages?: {
    id: string;
    backButton?: string;
    nextButton?: string;
    rows: {
      id: string;
      columns: (
        | {
            id: string;
            name: string;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'text';
            defaultValue?: string;
            maxLength?: number;
            minLength?: number;
            placeholder?: string;
          }
        | {
            id: string;
            name: string;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'textarea';
            defaultValue?: string;
            maxLength?: number;
            minLength?: number;
            placeholder?: string;
            rows: number;
          }
        | {
            id: string;
            name: string;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'email';
            defaultValue?: string;
            placeholder?: string;
          }
        | {
            id: string;
            name: string;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'number';
            defaultValue?: number;
            max?: number;
            min?: number;
            placeholder?: string;
            step?: number;
          }
        | {
            id: string;
            name: string;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'checkbox';
            defaultValue?: string[];
            options: {
              label: string;
              value: string;
            }[];
          }
        | {
            id: string;
            name: string;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'radio';
            defaultValue?: string;
            options: {
              label: string;
              value: string;
            }[];
          }
        | {
            id: string;
            name: string;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'select';
            defaultValue?: string;
            options: {
              label: string;
              value: string;
            }[];
            placeholder?: string;
          }
        | {
            id: string;
            name: string;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'date';
            defaultValue?: string;
            maxDate?: string;
            minDate?: string;
            placeholder?: string;
          }
        | {
            id: string;
            name: string;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'file';
            allowedFileTypes?: string;
            maxFileSize?: number;
            maxFiles?: number;
            relationTo?: string;
          }
        | {
            id: string;
            name: string;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'toggle';
            defaultValue?: boolean;
          }
        | {
            id: string;
            name: string;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'consent';
            defaultValue?: boolean;
          }
        | {
            id: string;
            type: 'message';
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            richText?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: 'ltr' | 'rtl' | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
            };
          }
        | {
            id: string;
            name: string;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'array';
            maxRows?: number;
            minRows?: number;
            rows: {
              id: string;
              columns: (
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'text';
                    defaultValue?: string;
                    maxLength?: number;
                    minLength?: number;
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'textarea';
                    defaultValue?: string;
                    maxLength?: number;
                    minLength?: number;
                    placeholder?: string;
                    rows: number;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'email';
                    defaultValue?: string;
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'number';
                    defaultValue?: number;
                    max?: number;
                    min?: number;
                    placeholder?: string;
                    step?: number;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'checkbox';
                    defaultValue?: string[];
                    options: {
                      label: string;
                      value: string;
                    }[];
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'radio';
                    defaultValue?: string;
                    options: {
                      label: string;
                      value: string;
                    }[];
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'select';
                    defaultValue?: string;
                    options: {
                      label: string;
                      value: string;
                    }[];
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'date';
                    defaultValue?: string;
                    maxDate?: string;
                    minDate?: string;
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'file';
                    allowedFileTypes?: string;
                    maxFileSize?: number;
                    maxFiles?: number;
                    relationTo?: string;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'toggle';
                    defaultValue?: boolean;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'consent';
                    defaultValue?: boolean;
                  }
              )[];
            }[];
          }
        | {
            id: string;
            name: string;
            errorMessage?: string;
            hidden: boolean;
            instructions?: string;
            label: string;
            required: boolean;
            conditions?: {
              conditions: {
                field: string;
                operator:
                  | 'equals'
                  | 'notEquals'
                  | 'greaterThan'
                  | 'lessThan'
                  | 'greaterThanOrEquals'
                  | 'lessThanOrEquals'
                  | 'contains'
                  | 'isEmpty'
                  | 'isNotEmpty'
                  | 'hasChanged'
                  | 'hasNotChanged';
                value?: string | number;
              }[];
              logic: 'and' | 'or';
            };
            type: 'group';
            rows: {
              id: string;
              columns: (
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'text';
                    defaultValue?: string;
                    maxLength?: number;
                    minLength?: number;
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'textarea';
                    defaultValue?: string;
                    maxLength?: number;
                    minLength?: number;
                    placeholder?: string;
                    rows: number;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'email';
                    defaultValue?: string;
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'number';
                    defaultValue?: number;
                    max?: number;
                    min?: number;
                    placeholder?: string;
                    step?: number;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'checkbox';
                    defaultValue?: string[];
                    options: {
                      label: string;
                      value: string;
                    }[];
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'radio';
                    defaultValue?: string;
                    options: {
                      label: string;
                      value: string;
                    }[];
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'select';
                    defaultValue?: string;
                    options: {
                      label: string;
                      value: string;
                    }[];
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'date';
                    defaultValue?: string;
                    maxDate?: string;
                    minDate?: string;
                    placeholder?: string;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'file';
                    allowedFileTypes?: string;
                    maxFileSize?: number;
                    maxFiles?: number;
                    relationTo?: string;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'toggle';
                    defaultValue?: boolean;
                  }
                | {
                    id: string;
                    name: string;
                    errorMessage?: string;
                    hidden: boolean;
                    instructions?: string;
                    label: string;
                    required: boolean;
                    conditions?: {
                      conditions: {
                        field: string;
                        operator:
                          | 'equals'
                          | 'notEquals'
                          | 'greaterThan'
                          | 'lessThan'
                          | 'greaterThanOrEquals'
                          | 'lessThanOrEquals'
                          | 'contains'
                          | 'isEmpty'
                          | 'isNotEmpty'
                          | 'hasChanged'
                          | 'hasNotChanged';
                        value?: string | number;
                      }[];
                      logic: 'and' | 'or';
                    };
                    type: 'consent';
                    defaultValue?: boolean;
                  }
              )[];
            }[];
          }
      )[];
    }[];
    title: string;
  }[];
  confirmationType?: ('redirect' | 'message') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirectUrl?: string | null;
  redirect?: string | null;
  notification?:
    | {
        email: string;
        cc?: string | null;
        bcc?: string | null;
        subject: string;
        message: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        conditions?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  formSchema?: Record<string, unknown> | null;
  /**
   * The form field whose value is stored as the submission identifier, shown in the submissions list.
   */
  identifierField?: string | null;
  /**
   * Schema path used for rich text content field (message)
   */
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: string;
  /**
   * Auto-generated from form title at submission time
   */
  title: string;
  /**
   * Value of the nominated identifier field at submission time
   */
  identifier?: string | null;
  /**
   * Reference to parent form (for grouping/queries)
   */
  form?: (string | null) | Form;
  submissionData: Record<string, any> | null;
  formSnapshot?: Record<string, any> | null;
  userAgent?: string | null;
  ipAddress?: string | null;
  fileUploads?: Array<{fieldName: string; ids: string[]; maxFiles: number; relationTo: string}> | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Files uploaded via form submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-uploads".
 */
export interface FormUpload {
  id: string;
  /**
   * The form this file was uploaded through
   */
  form?: (string | null) | Form;
  /**
   * The submission this file belongs to
   */
  submission?: (string | null) | Submission;
  /**
   * The form field name this file was uploaded to
   */
  fieldName?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_item".
 */
export interface MenuItem {
  id: string;
  _order?: string | null;
  type?: ('url' | 'internal' | 'custom' | 'passive') | null;
  title: string;
  navigation: string | Navigation;
  parent?: (string | null) | MenuItem;
  url?: string | null;
  internal?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null);
  custom?: string | null;
  passive?: string | null;
  collapsed?: boolean | null;
  depth?: number | null;
  href?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'sessions';
        value: string | Session;
      } | null)
    | ({
        relationTo: 'accounts';
        value: string | Account;
      } | null)
    | ({
        relationTo: 'verifications';
        value: string | Verification;
      } | null)
    | ({
        relationTo: 'passkeys';
        value: string | Passkey;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'submissions';
        value: string | Submission;
      } | null)
    | ({
        relationTo: 'form-uploads';
        value: string | FormUpload;
      } | null)
    | ({
        relationTo: 'navigation';
        value: string | Navigation;
      } | null)
    | ({
        relationTo: 'menu_item';
        value: string | MenuItem;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  quality?: T;
  optimise?: T;
  resizeWidth?: T;
  resizeHeight?: T;
  fit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  description?: T;
  image?: T;
  blocks?: T | {};
  article?:
    | T
    | {
        blocks?: T | {};
      };
  listing?:
    | T
    | {
        list?: T;
        limit?: T;
        items?: T;
        footer?: T | {};
      };
  contact?:
    | T
    | {
        blocks?: T | {};
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        robots?:
          | T
          | {
              nofollow?: T;
              noindex?: T;
              noarchive?: T;
              nocache?: T;
              extras?: T;
            };
        languageAlternates?:
          | T
          | {
              href?: T;
              hrefLang?: T;
              id?: T;
            };
        openGraph?:
          | T
          | {
              basic?:
                | T
                | {
                    title?: T;
                    type?: T;
                    image?: T;
                    url?: T;
                  };
              optional?:
                | T
                | {
                    audio?: T;
                    description?: T;
                    determiner?: T;
                    locale?: T;
                    localeAlternate?:
                      | T
                      | {
                          locale?: T;
                          id?: T;
                        };
                    siteName?: T;
                    video?: T;
                  };
              image?:
                | T
                | {
                    type?: T;
                    width?: T;
                    height?: T;
                    alt?: T;
                  };
              article?:
                | T
                | {
                    publishedTime?: T;
                    modifiedTime?: T;
                    expirationTime?: T;
                    authors?:
                      | T
                      | {
                          author?: T;
                          id?: T;
                        };
                    section?: T;
                    tags?:
                      | T
                      | {
                          tag?: T;
                          id?: T;
                        };
                  };
            };
        twitter?:
          | T
          | {
              card?: T;
              site?: T;
              creator?: T;
              title?: T;
              description?: T;
              image?: T;
              imageAlt?: T;
            };
        extend?:
          | T
          | {
              link?:
                | T
                | {
                    rel?: T;
                    href?: T;
                    hreflang?: T;
                    type?: T;
                    id?: T;
                  };
              meta?:
                | T
                | {
                    name?: T;
                    property?: T;
                    content?: T;
                    id?: T;
                  };
            };
      };
  generateSlug?: T;
  slug?: T;
  template?: T;
  author?: T;
  theme?: T;
  menu?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        robots?:
          | T
          | {
              nofollow?: T;
              noindex?: T;
              noarchive?: T;
              nocache?: T;
              extras?: T;
            };
        languageAlternates?:
          | T
          | {
              href?: T;
              hrefLang?: T;
              id?: T;
            };
        openGraph?:
          | T
          | {
              basic?:
                | T
                | {
                    title?: T;
                    type?: T;
                    image?: T;
                    url?: T;
                  };
              optional?:
                | T
                | {
                    audio?: T;
                    description?: T;
                    determiner?: T;
                    locale?: T;
                    localeAlternate?:
                      | T
                      | {
                          locale?: T;
                          id?: T;
                        };
                    siteName?: T;
                    video?: T;
                  };
              image?:
                | T
                | {
                    type?: T;
                    width?: T;
                    height?: T;
                    alt?: T;
                  };
              article?:
                | T
                | {
                    publishedTime?: T;
                    modifiedTime?: T;
                    expirationTime?: T;
                    authors?:
                      | T
                      | {
                          author?: T;
                          id?: T;
                        };
                    section?: T;
                    tags?:
                      | T
                      | {
                          tag?: T;
                          id?: T;
                        };
                  };
            };
        twitter?:
          | T
          | {
              card?: T;
              site?: T;
              creator?: T;
              title?: T;
              description?: T;
              image?: T;
              imageAlt?: T;
            };
        extend?:
          | T
          | {
              link?:
                | T
                | {
                    rel?: T;
                    href?: T;
                    hreflang?: T;
                    type?: T;
                    id?: T;
                  };
              meta?:
                | T
                | {
                    name?: T;
                    property?: T;
                    content?: T;
                    id?: T;
                  };
            };
      };
  generateSlug?: T;
  slug?: T;
  theme?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  image?: T;
  role?: T;
  emailVerified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  expiresAt?: T;
  token?: T;
  ipAddress?: T;
  userAgent?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  accountId?: T;
  providerId?: T;
  user?: T;
  accessToken?: T;
  refreshToken?: T;
  idToken?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  scope?: T;
  password?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications_select".
 */
export interface VerificationsSelect<T extends boolean = true> {
  identifier?: T;
  value?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "passkeys_select".
 */
export interface PasskeysSelect<T extends boolean = true> {
  name?: T;
  publicKey?: T;
  user?: T;
  credentialID?: T;
  counter?: T;
  deviceType?: T;
  backedUp?: T;
  transports?: T;
  aaguid?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  locked?: T;
  pages?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirectUrl?: T;
  redirect?: T;
  notification?:
    | T
    | {
        email?: T;
        cc?: T;
        bcc?: T;
        subject?: T;
        message?: T;
        conditions?: T;
        id?: T;
      };
  formSchema?: T;
  identifierField?: T;
  richText?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  title?: T;
  identifier?: T;
  form?: T;
  submissionData?: T;
  formSnapshot?: T;
  userAgent?: T;
  ipAddress?: T;
  fileUploads?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-uploads_select".
 */
export interface FormUploadsSelect<T extends boolean = true> {
  form?: T;
  submission?: T;
  fieldName?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  items?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_item_select".
 */
export interface MenuItemSelect<T extends boolean = true> {
  _order?: T;
  type?: T;
  title?: T;
  navigation?: T;
  parent?: T;
  url?: T;
  internal?: T;
  custom?: T;
  passive?: T;
  collapsed?: T;
  depth?: T;
  href?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  blocks?: (Hero | TextBlock | FormBlock | RelatedBlocks | ImageBlock)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    /**
     * Canonical URL for this page
     */
    canonical?: string | null;
    robots?: {
      nofollow?: boolean | null;
      noindex?: boolean | null;
      noarchive?: boolean | null;
      nocache?: boolean | null;
      /**
       * Additional robots directives
       */
      extras?: string | null;
    };
    languageAlternates?:
      | {
          href: string;
          hrefLang: string;
          id?: string | null;
        }[]
      | null;
    openGraph?: {
      basic?: {
        title?: string | null;
        type?: string | null;
        /**
         * Open Graph image
         */
        image?: (string | null) | Media;
        url?: string | null;
      };
      optional?: {
        audio?: string | null;
        description?: string | null;
        determiner?: string | null;
        locale?: string | null;
        localeAlternate?:
          | {
              locale: string;
              id?: string | null;
            }[]
          | null;
        siteName?: string | null;
        video?: string | null;
      };
      /**
       * Additional image properties (optional)
       */
      image?: {
        /**
         * MIME type (e.g., image/jpeg)
         */
        type?: string | null;
        width?: number | null;
        height?: number | null;
        alt?: string | null;
      };
      article?: {
        publishedTime?: string | null;
        modifiedTime?: string | null;
        expirationTime?: string | null;
        authors?:
          | {
              author: string;
              id?: string | null;
            }[]
          | null;
        section?: string | null;
        tags?:
          | {
              tag: string;
              id?: string | null;
            }[]
          | null;
      };
    };
    twitter?: {
      card?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
      /**
       * Twitter @username for the site
       */
      site?: string | null;
      /**
       * Twitter @username for the content creator
       */
      creator?: string | null;
      title?: string | null;
      description?: string | null;
      /**
       * Twitter card image
       */
      image?: (string | null) | Media;
      /**
       * Alt text for the Twitter image
       */
      imageAlt?: string | null;
    };
    extend?: {
      link?:
        | {
            rel?: string | null;
            href?: string | null;
            hreflang?: string | null;
            type?: string | null;
            id?: string | null;
          }[]
        | null;
      meta?:
        | {
            name?: string | null;
            property?: string | null;
            content?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  title: string;
  theme?: ('light' | 'dark' | 'primary' | 'secondary' | 'tertiary') | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    /**
     * Canonical URL for this page
     */
    canonical?: string | null;
    robots?: {
      nofollow?: boolean | null;
      noindex?: boolean | null;
      noarchive?: boolean | null;
      nocache?: boolean | null;
      /**
       * Additional robots directives
       */
      extras?: string | null;
    };
    languageAlternates?:
      | {
          href: string;
          hrefLang: string;
          id?: string | null;
        }[]
      | null;
    openGraph?: {
      basic?: {
        title?: string | null;
        type?: string | null;
        /**
         * Open Graph image
         */
        image?: (string | null) | Media;
        url?: string | null;
      };
      optional?: {
        audio?: string | null;
        description?: string | null;
        determiner?: string | null;
        locale?: string | null;
        localeAlternate?:
          | {
              locale: string;
              id?: string | null;
            }[]
          | null;
        siteName?: string | null;
        video?: string | null;
      };
      /**
       * Additional image properties (optional)
       */
      image?: {
        /**
         * MIME type (e.g., image/jpeg)
         */
        type?: string | null;
        width?: number | null;
        height?: number | null;
        alt?: string | null;
      };
      article?: {
        publishedTime?: string | null;
        modifiedTime?: string | null;
        expirationTime?: string | null;
        authors?:
          | {
              author: string;
              id?: string | null;
            }[]
          | null;
        section?: string | null;
        tags?:
          | {
              tag: string;
              id?: string | null;
            }[]
          | null;
      };
    };
    twitter?: {
      card?: ('summary' | 'summary_large_image' | 'app' | 'player') | null;
      /**
       * Twitter @username for the site
       */
      site?: string | null;
      /**
       * Twitter @username for the content creator
       */
      creator?: string | null;
      title?: string | null;
      description?: string | null;
      /**
       * Twitter card image
       */
      image?: (string | null) | Media;
      /**
       * Alt text for the Twitter image
       */
      imageAlt?: string | null;
    };
    extend?: {
      link?:
        | {
            rel?: string | null;
            href?: string | null;
            hreflang?: string | null;
            type?: string | null;
            id?: string | null;
          }[]
        | null;
      meta?:
        | {
            name?: string | null;
            property?: string | null;
            content?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  blocks?: T | {};
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        robots?:
          | T
          | {
              nofollow?: T;
              noindex?: T;
              noarchive?: T;
              nocache?: T;
              extras?: T;
            };
        languageAlternates?:
          | T
          | {
              href?: T;
              hrefLang?: T;
              id?: T;
            };
        openGraph?:
          | T
          | {
              basic?:
                | T
                | {
                    title?: T;
                    type?: T;
                    image?: T;
                    url?: T;
                  };
              optional?:
                | T
                | {
                    audio?: T;
                    description?: T;
                    determiner?: T;
                    locale?: T;
                    localeAlternate?:
                      | T
                      | {
                          locale?: T;
                          id?: T;
                        };
                    siteName?: T;
                    video?: T;
                  };
              image?:
                | T
                | {
                    type?: T;
                    width?: T;
                    height?: T;
                    alt?: T;
                  };
              article?:
                | T
                | {
                    publishedTime?: T;
                    modifiedTime?: T;
                    expirationTime?: T;
                    authors?:
                      | T
                      | {
                          author?: T;
                          id?: T;
                        };
                    section?: T;
                    tags?:
                      | T
                      | {
                          tag?: T;
                          id?: T;
                        };
                  };
            };
        twitter?:
          | T
          | {
              card?: T;
              site?: T;
              creator?: T;
              title?: T;
              description?: T;
              image?: T;
              imageAlt?: T;
            };
        extend?:
          | T
          | {
              link?:
                | T
                | {
                    rel?: T;
                    href?: T;
                    hreflang?: T;
                    type?: T;
                    id?: T;
                  };
              meta?:
                | T
                | {
                    name?: T;
                    property?: T;
                    content?: T;
                    id?: T;
                  };
            };
      };
  title?: T;
  theme?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        robots?:
          | T
          | {
              nofollow?: T;
              noindex?: T;
              noarchive?: T;
              nocache?: T;
              extras?: T;
            };
        languageAlternates?:
          | T
          | {
              href?: T;
              hrefLang?: T;
              id?: T;
            };
        openGraph?:
          | T
          | {
              basic?:
                | T
                | {
                    title?: T;
                    type?: T;
                    image?: T;
                    url?: T;
                  };
              optional?:
                | T
                | {
                    audio?: T;
                    description?: T;
                    determiner?: T;
                    locale?: T;
                    localeAlternate?:
                      | T
                      | {
                          locale?: T;
                          id?: T;
                        };
                    siteName?: T;
                    video?: T;
                  };
              image?:
                | T
                | {
                    type?: T;
                    width?: T;
                    height?: T;
                    alt?: T;
                  };
              article?:
                | T
                | {
                    publishedTime?: T;
                    modifiedTime?: T;
                    expirationTime?: T;
                    authors?:
                      | T
                      | {
                          author?: T;
                          id?: T;
                        };
                    section?: T;
                    tags?:
                      | T
                      | {
                          tag?: T;
                          id?: T;
                        };
                  };
            };
        twitter?:
          | T
          | {
              card?: T;
              site?: T;
              creator?: T;
              title?: T;
              description?: T;
              image?: T;
              imageAlt?: T;
            };
        extend?:
          | T
          | {
              link?:
                | T
                | {
                    rel?: T;
                    href?: T;
                    hreflang?: T;
                    type?: T;
                    id?: T;
                  };
              meta?:
                | T
                | {
                    name?: T;
                    property?: T;
                    content?: T;
                    id?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    global?: 'home' | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}